#!/bin/bash
# Multi-direction test for check_style_guide.py, on its own scratch fixture
# (practice: fixture-owns-its-state), never on the repo it happens to run in:
#   1. no repo-local visual practices               -- SKIPPED (exit 2);
#   2. all four, well formed, guide generated       -- clean;
#   3. one practice missing                         -- fires;
#   4. the guide hand-edited                        -- fires as stale;
#   5. an off-palette color in finished work        -- fires;
#   6. the same color in a declared sketch          -- clean;
#   7. a gradient, a stray font, an undersized logo -- each fires.
set -euo pipefail
cd "$(dirname "$0")/../../.."
SET_ROOT="$(pwd)"
CHECK="$SET_ROOT/tools/checks/check_style_guide.py"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
export PRECEDENT_CHECK_ROOT="$SCRATCH"

expect () {  # expect CODE PATTERN DESCRIPTION
  set +e
  OUT="$(python3 "$CHECK" 2>&1)"
  CODE=$?
  set -e
  if [[ $CODE -ne $1 ]] || ! grep -q -- "$2" <<<"$OUT"; then
    echo "FAIL: $3 -- expected exit $1 and \"$2\", got exit $CODE:" >&2
    echo "$OUT" >&2
    exit 1
  fi
  echo "ok: $3"
}

P="$SCRATCH/local/practices"
mkdir -p "$P" "$SCRATCH/content/logo"
cat > "$SCRATCH/precedent.json" <<'EOF'
{"format_version": 1, "sources": [{"level": "repo-local", "name": "local", "path": "local"}]}
EOF

expect 2 "SKIPPED: no visual identity" "SKIPPED when no visual practice exists"

fm () {  # fm SLUG [APPLIES_TO]
  printf -- '---\nslug:        %s\napplies_to:  %s\nadded:       "2026-01-01"\napproved_by: "Tester, 2026-01-01 (strength: decided)"\n---\n## Rule\n' \
    "$1" "${2:-[\"content/**\"]}"
}
{ fm visual-logo; cat <<'EOF'
**The mark is Example Box:** a square with a dot.

| File | Use |
|---|---|
| [Logo](../../content/logo/example-logo.svg) | Light backgrounds |
| [Logo, dark](../../content/logo/example-logo-dark.svg) | Dark backgrounds |
| [Favicon](../../content/logo/example-favicon.svg) | Under 32px |

- **Two colors:** ink and accent.
- **One color** when two won't print.
- **Smallest size:** 32px tall. Below that, the favicon.
- **Clear space:** half the mark's height.
- **Lockup:** mark left, name right.
- **Don't** stretch it.
- **Sketches:** files in `content/logo/` not named `example-*` are exempt from the color and type rules.

## Why
Fixture.
EOF
} > "$P/visual-logo.md"
{ fm visual-palette '["content/**/*.html", "content/**/*.svg", "content/**/*.css"]'; cat <<'EOF'
| Name | Light | Dark | Use |
|---|---|---|---|
| Ink | `#111111` | `#EEEEEE` | Text |
| Accent | `#224488` | `#88AAEE` | Links |

No gradients.
EOF
} > "$P/visual-palette.md"
{ fm visual-type; cat <<'EOF'
| Role | Face |
|---|---|
| Headings | `Literata` |
| Body | `Inter` |

Both free on Google Fonts.
EOF
} > "$P/visual-type.md"
{ fm visual-imagery; cat <<'EOF'
- **Show people at work.**
- **No robots.**
EOF
} > "$P/visual-imagery.md"
for f in example-logo example-logo-dark example-favicon; do
  printf '<svg xmlns="http://www.w3.org/2000/svg"><rect fill="#111111"/></svg>\n' \
    > "$SCRATCH/content/logo/$f.svg"
done
cat > "$SCRATCH/content/page.html" <<'EOF'
<style>body { color: #111111; font-family: "Inter", sans-serif; }</style>
<a href="#top">top</a>
<img src="logo/example-logo.svg" width="64">
EOF

expect 1 "VISUAL_STYLE_GUIDE.md: missing" "fires when the guide was never generated"
python3 "$CHECK" --write 2>/dev/null
grep -q '^<!-- Generated by tools/checks/check_style_guide.py' "$SCRATCH/content/VISUAL_STYLE_GUIDE.md"
grep -q 'src="logo/example-logo.svg" alt="The logo, Example Box"' "$SCRATCH/content/VISUAL_STYLE_GUIDE.md"
grep -q '(logo/example-favicon.svg)' "$SCRATCH/content/VISUAL_STYLE_GUIDE.md"
echo "ok: --write builds the guide, with its marker, header logo and relinked files"
expect 0 "" "clean on four well-formed practices and a generated guide"

mv "$P/visual-type.md" "$SCRATCH/type.md"
expect 1 "visual-type: missing" "fires when one of the four is missing"
mv "$SCRATCH/type.md" "$P/visual-type.md"

echo "hand edit" >> "$SCRATCH/content/VISUAL_STYLE_GUIDE.md"
expect 1 "differs from its practices" "fires on a hand-edited guide"
python3 "$CHECK" --write 2>/dev/null

echo '<p style="color: #ff0000">x</p>' >> "$SCRATCH/content/page.html"
expect 1 "page.html:4: #ff0000 is not in the palette" "fires on an off-palette color in finished work"
sed -i '$d' "$SCRATCH/content/page.html"

printf '<svg><rect fill="#ff0000"/></svg>\n' > "$SCRATCH/content/logo/idea-2.svg"
expect 0 "" "a declared sketch is exempt"

echo '<div style="background: linear-gradient(#111111, #224488)"></div>' >> "$SCRATCH/content/page.html"
expect 1 "a gradient, and the palette says none" "fires on a gradient when the palette forbids them"
sed -i '$d' "$SCRATCH/content/page.html"

echo '<p style="font-family: Comic Sans MS">x</p>' >> "$SCRATCH/content/page.html"
expect 1 'font-family "Comic Sans MS" is not in the type table' "fires on a font outside the type table"
sed -i '$d' "$SCRATCH/content/page.html"

echo '<img src="logo/example-logo.svg" height="16">' >> "$SCRATCH/content/page.html"
expect 1 "under the smallest size of 32px" "fires on a logo shown under its smallest size"
sed -i '$d' "$SCRATCH/content/page.html"
echo '<img src="logo/example-favicon.svg" height="16">' >> "$SCRATCH/content/page.html"
expect 0 "" "the small-size file may be shown small"
