#!/usr/bin/env python3
"""todo/TODO.md and todo/CLOSED.md, generated from todo/*.md's frontmatter

build_todo_index.py — the ongoing generator for spec/OPEN_ITEM_AND_GOTCHA_PLAN.md's
open-item format (Part 1). Reads every `todo/todo-*.md` file's frontmatter and
writes two generated files, the way tools/build_views.py generates AGENTS.md's
loader block, MAP.md and GLOSSARY.md from practices/*.md: hand-editing either
output fails the check, because the fields in todo/*.md are the only place
any of this is meant to be edited.

  - todo/TODO.md — every `status: open` item, sectioned: one table per
    `kind`, one table per `batch`, Unblocked work (open, kind: analysis,
    no blocked_on -- this is the list that should be closest to empty),
    Open decisions (open, kind: decision), and Due Reminders (open,
    disposition: ask, remind_on has arrived).
  - todo/CLOSED.md — every `status: done` or `status: dropped` item, one
    line each, newest-closed-first. Nobody reads this file routinely; it
    exists so a closed item is still findable without living where an
    open one would be seen.

Run:
  python3 tools/build_todo_index.py             # write todo/TODO.md, todo/CLOSED.md
  python3 tools/build_todo_index.py --check      # regenerate to memory, diff
                                                  # against the committed files,
                                                  # exit 1 on any diff
  python3 tools/build_todo_index.py --repo DIR [--check]
      # operate on DIR/todo/ instead of this repo's own
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import precedent_time  # practice: timestamps-carry-offset
import summary_text  # links out BEFORE any cut -- see its docstring
import title_case  # practice: headline-capitalization -- applied by tool,
                   # never by hand, on every heading this file generates

# The label every generated file opens with (tools/generated_files.json
# lists them all; Morgan, 2026-09-29): visible as a table on GitHub.
GENERATED_HEADER = (
    '---\n'
    'generated_by: tools/build_todo_index.py\n'
    'edit_instead: "todo/todo-*.md"\n'
    'note: "Generated by tools/build_todo_index.py. Don\'t edit here; edit todo/todo-*.md instead, then run python3 tools/build_todo_index.py."\n'
    '---'
)


def _todo_header(as_of):
    """TODO.md's header: GENERATED_HEADER plus the date its ages and due
    reminders were computed on.

    code-cites-practice: generated-files-registered

    WHY `as_of`. The Age column and the Due Reminders section are relative
    to a day, so a committed TODO.md went out of date at every midnight
    and read one day older in a zone already past it. --as-ci --isolated
    runs under TZ=UTC, and on 2026-09-29 at 22:00 in Buenos Aires it was
    already the 30th there: every age came out one day greater and the
    deep check refused a push that had not touched todo/ at all. --check
    now rebuilds against the date the file records, so it tests that the
    file matches its items, not that someone regenerated it since midnight
    (practice: timestamps-carry-offset).
    """
    return GENERATED_HEADER[:-len('---')] + f'as_of: {as_of}\n---'


def recorded_as_of(path):
    """-> the `as_of:` date a generated TODO.md records, or None."""
    try:
        head = path.read_text(encoding='utf-8').split('\n---', 1)[0]
    except OSError:
        return None
    m = re.search(r'^as_of:\s*(\d{4}-\d{2}-\d{2})\s*$', head, re.M)
    return m.group(1) if m else None

FM_FIELD_RE = re.compile(r'^([a-z_]+):\s*(.*)$')

KIND_LABELS = {
    'analysis': 'Analyses (agent-doable)',
    'verify': 'Verify before external use',
    'manual': 'Manual (needs a person to act)',
    'decision': 'Decisions (the person\'s call)',
}
KIND_ORDER = ['analysis', 'verify', 'manual', 'decision']
# Kinds people reach for that are not one of the four; the refusal suggests
# `manual` for these (2026-10-10, a consumer's item filed as `task`).
KIND_SYNONYMS = {'task', 'todo', 'action', 'chore'}

# spec/OPEN_ITEM_AND_GOTCHA_PLAN.md's own frontmatter table: status is
# open | done | dropped, nothing else. An item outside this set (`closed`
# is the one that has actually shipped -- valid elsewhere in this repo's
# OTHER status vocabulary, tools/doc_lifecycle.py's briefs and records,
# which makes it an easy value to reach for by mistake) does not raise
# here on its own; it silently fails BOTH `status == 'open'` and
# `status in ('done', 'dropped')` below and vanishes from both generated
# files with no error. Found 2026-09-18 already live on two items in this
# repo. Caught here, at read time, so a bad status fails loud instead of
# just going missing from the reader's view.
LEGAL_STATUS = ('open', 'done', 'dropped')


class TodoItem:
    def __init__(self, path, fields):
        self.path = path
        self.fields = fields

    def get(self, key, default=None):
        v = self.fields.get(key)
        if v is None or v == 'null':
            return default
        return v

    @property
    def slug(self):
        return self.get('slug') or self.path.stem

    @property
    def title(self):
        text = self.path.read_text(encoding='utf-8')
        m = re.search(r'^##\s*What\s*\n+(.*?)(?:\n\n|\Z)', text,
                       re.MULTILINE | re.DOTALL)
        if not m:
            return self.slug
        body = m.group(1)
        tm = re.search(r'\*\*(.+?)\*\*', body, re.DOTALL)
        one_line = tm.group(1) if tm else body.splitlines()[0]
        return summary_text.one_line(one_line, 120)


def _unquote(v):
    v = v.strip()
    if v == 'null' or v == '':
        return None
    if v.startswith('"') and v.endswith('"'):
        return v[1:-1].replace('\\"', '"')
    return v


def read_todo_item(path):
    text = path.read_text(encoding='utf-8')
    if not text.startswith('---\n'):
        sys.exit(f'build_todo_index FAIL: {path} has no frontmatter fence.')
    end = text.find('\n---', 4)
    if end == -1:
        sys.exit(f'build_todo_index FAIL: {path} frontmatter never closes.')
    fm_text = text[4:end]
    fields = {}
    for line in fm_text.splitlines():
        if not line.strip():
            continue
        m = FM_FIELD_RE.match(line)
        if not m:
            continue
        fields[m.group(1)] = _unquote(m.group(2))
    item = TodoItem(path, fields)
    status = item.get('status', 'open')
    if status not in LEGAL_STATUS:
        sys.exit(f'build_todo_index FAIL: {path} has status: {status!r}, '
                  f'not one of {", ".join(LEGAL_STATUS)} -- it would '
                  f'silently vanish from both TODO.md and CLOSED.md rather '
                  f'than fail loud. Fix the frontmatter (an item is `open` '
                  f'until finished, then `done` or `dropped`, never '
                  f'`closed` -- that value belongs to this repo\'s other '
                  f'status vocabulary, tools/doc_lifecycle.py\'s briefs and '
                  f'records, not to a todo item).')
    kind = item.get('kind')
    if status == 'open' and kind not in KIND_ORDER:
        sys.exit(f'build_todo_index FAIL: {path} is open with kind: '
                  f'{kind!r}, not one of {", ".join(KIND_ORDER)} -- '
                  f'TODO.md has no table for it, so it would silently '
                  f'vanish from the open-items list. Pick one: `analysis` '
                  f'(a bug or question to work out), `verify` (something to '
                  f'check is true), `manual` (a person has to do something), '
                  f'`decision` (a person has to choose)'
                  + (f'. A `{kind}` is usually `manual`.'
                     if str(kind).lower() in KIND_SYNONYMS else '.'))
    return item


def load_items(todo_dir):
    if not todo_dir.exists():
        return []
    return [read_todo_item(p) for p in sorted(todo_dir.glob('todo-*.md'))]


def age_days(noted, today):
    try:
        from datetime import date
        n = date.fromisoformat(noted)
        t = date.fromisoformat(today)
        return (t - n).days
    except (ValueError, TypeError):
        return None


def _row(item, today, extra=''):
    age = age_days(item.get('noted'), today)
    age_s = f'{age}d' if age is not None else '?'
    link = f'[`{item.slug}`]({item.slug}.md)'
    disp = item.get('disposition', 'wait')
    blocked = item.get('blocked_on')
    blocked_s = summary_text.one_line(blocked, 80, '…')
    return f'| {link} | {item.title} | {age_s} | {disp} | {blocked_s}{extra} |'


def _h(text):
    """practice: headline-capitalization -- applied by tool, on every
    heading this generator writes, never typed in by hand."""
    return title_case.title_case(text)


def render_todo_md(items, today):
    open_items = [it for it in items if it.get('status', 'open') == 'open']
    lines = [_todo_header(today), '', f'# {_h("TODO — open items")}', '']

    for kind in KIND_ORDER:
        rows = [it for it in open_items if it.get('kind') == kind]
        if not rows:
            continue
        rows.sort(key=lambda it: it.get('noted') or '')
        lines += [f'## {_h(KIND_LABELS[kind])}', '',
                  '| Item | What | Age | Disposition | Blocked on |',
                  '|---|---|---|---|---|']
        for it in rows:
            lines.append(_row(it, today))
        lines.append('')

    batches = sorted({it.get('batch') for it in open_items if it.get('batch')})
    for batch in batches:
        rows = [it for it in open_items if it.get('batch') == batch]
        rows.sort(key=lambda it: it.get('noted') or '')
        lines += [f'## {_h(f"Batch: {batch}")}', '',
                  '| Item | What | Age | Disposition | Blocked on |',
                  '|---|---|---|---|---|']
        for it in rows:
            lines.append(_row(it, today))
        lines.append('')

    unblocked = [it for it in open_items
                 if it.get('kind') == 'analysis' and not it.get('blocked_on')]
    unblocked.sort(key=lambda it: it.get('noted') or '')
    lines += [f'## {_h("Unblocked work")}', '',
              '(every open, kind: analysis item with no blocked_on -- this '
              'list should be closest to empty)', '']
    if unblocked:
        lines += ['| Item | What | Age |', '|---|---|---|']
        for it in unblocked:
            lines.append(f'| [`{it.slug}`]({it.slug}.md) | {it.title} | '
                          f'{age_days(it.get("noted"), today)}d |')
    else:
        lines.append('(none)')
    lines.append('')

    decisions = [it for it in open_items if it.get('kind') == 'decision']
    decisions.sort(key=lambda it: it.get('noted') or '')
    lines += [f'## {_h("Open decisions")}', '']
    if decisions:
        lines += ['| Item | What | Waiting on |', '|---|---|---|']
        for it in decisions:
            lines.append(f'| [`{it.slug}`]({it.slug}.md) | {it.title} | '
                          f'{it.get("waiting_on") or ""} |')
    else:
        lines.append('(none)')
    lines.append('')

    due = due_items(open_items, today)
    lines += [f'## {_h("Due Reminders")}', '']
    if due:
        lines += ['| Item | What | Due since |', '|---|---|---|']
        for it in due:
            lines.append(f'| [`{it.slug}`]({it.slug}.md) | {it.title} | '
                          f'{it.get("remind_on")} |')
    else:
        lines.append('(none due)')
    lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def due_items(items, today):
    """Open `disposition: ask` items whose `remind_on` has arrived, the
    longest-due first: the one definition of a due reminder, read by
    TODO.md's Due Reminders table and by the reply gate's remind() below
    (practice: todo-reminder)."""
    due = [it for it in items
           if it.get('status', 'open') == 'open'
           and it.get('disposition') == 'ask' and it.get('remind_on')
           and it.get('remind_on') <= today]
    due.sort(key=lambda it: it.get('remind_on') or '')
    return due


def remind(root, transcript=None):
    """The reply gate's block: the longest-due reminder this conversation
    has not shown yet, for the Boildown's Todo line, or '' when none is due.

    WHY, 2026-10-10. A due reminder was listed in TODO.md's table and
    nowhere a person looks: the Boildown's one Todo was picked by topic, so
    four reminders sat due for 10 to 21 days without one reaching Morgan.
    His fix: "Maybe we should have it show one BY DATE, like when something
    is due" (strength: decided).

    Once per conversation per item: a reminder whose slug any earlier reply
    in the transcript already carries is skipped, so it is raised, not
    nagged. It leaves the list for good when the person answers it -- done,
    a new `remind_on`, or "Drop it" (`parked`). Local files only; a todo
    directory this cannot read prints nothing rather than take the gate
    down (practice: fail-gracefully)."""
    root = pathlib.Path(root)
    try:
        due = due_items(load_items(root / 'todo'),
                        precedent_time.today(root))
    except (SystemExit, OSError, ValueError):
        return ''
    if not due:
        return ''
    shown = ''
    if transcript and pathlib.Path(transcript).is_file():
        try:
            import precedent_reply_check as prc
            shown = '\n'.join(t for _, t in
                               (prc.assistant_timeline(transcript) or []))
        except Exception:                                    # noqa: BLE001
            shown = ''
    fresh = [it for it in due if it.slug not in shown]
    if not fresh:
        return ''
    it = fresh[0]
    others = len(due) - 1
    more = (f' {others} other reminder(s) are due too; this conversation '
            f'raises one at a time.' if others else '')
    return (f"DUE REMINDER (todo-reminder): the Boildown's Todo line is this "
            f"one, by date, ahead of any pick by topic. Introduce it as \"A "
            f"reminder you asked for, due since {it.get('remind_on')}:\", "
            f"link it, and ask whether it is done, gets a new date, or is "
            f"dropped: {it.title} -- todo/{it.slug}.md.{more}")


def render_closed_md(items):
    closed = [it for it in items if it.get('status') in ('done', 'dropped')]
    closed.sort(key=lambda it: it.get('closed') or it.get('noted') or '',
                reverse=True)
    lines = [GENERATED_HEADER, '', f'# {_h("CLOSED — done and dropped items")}', '']
    if closed:
        lines += ['| Item | What | Status | Closed |', '|---|---|---|---|']
        for it in closed:
            lines.append(f'| [`{it.slug}`]({it.slug}.md) | {it.title} | '
                          f'{it.get("status")} | {it.get("closed") or ""} |')
    else:
        lines.append('(none)')
    lines.append('')
    return '\n'.join(lines).rstrip() + '\n'



def register_outputs(repo):
    """List this tool's outputs in the repository's own
    tools/generated_files.json when it keeps one (precedent_regenerate.
    register says why). -> the paths added. An engine too old to carry the
    helper lists nothing, as before."""
    try:
        import precedent_regenerate as rg
    except ImportError:
        return []
    return rg.register(repo, rg.own_entries('tools/build_todo_index.py', ['todo/TODO.md', 'todo/CLOSED.md'],
                                            'todo/todo-*.md'))

def main(argv):
    repo = ROOT
    check = False
    rest = list(argv)
    while rest:
        a = rest.pop(0)
        if a == '--repo':
            repo = pathlib.Path(rest.pop(0)).resolve()
        elif a == '--check':
            check = True
        elif a in ('--help', '-h'):
            print((__doc__ or '').strip())
            return 0
        else:
            sys.exit(f'build_todo_index FAIL: unknown argument {a!r}.')

    todo_dir = repo / 'todo'
    items = load_items(todo_dir)
    today = precedent_time.today(repo)
    if check:
        # Rebuild against the day the committed file was computed on, so an
        # age that grew overnight is not drift (_todo_header says why).
        today = recorded_as_of(todo_dir / 'TODO.md') or today

    outputs = {
        todo_dir / 'TODO.md': render_todo_md(items, today),
        todo_dir / 'CLOSED.md': render_closed_md(items),
    }

    if check:
        drift = False
        for path, want in outputs.items():
            have = path.read_text(encoding='utf-8') if path.exists() else None
            if have != want:
                print(f'build_todo_index: DRIFT in {path}')
                drift = True
        if drift:
            print('build_todo_index: drift found -- run without --check to '
                  'regenerate, or edit the item files in todo/ instead.')
            return 1
        print(f'build_todo_index: {len(outputs)} generated file(s) match, '
              f'0 drift, {len(items)} item(s) read.')
        return 0

    todo_dir.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content, encoding='utf-8')
    print(f'build_todo_index: wrote {len(outputs)} file(s) from '
          f'{len(items)} item(s):')
    for path in outputs:
        print(f'  {path.relative_to(repo)}')
    for rel in register_outputs(repo):
        print(f'  tools/generated_files.json: now lists {rel}')
    return 0


if __name__ == '__main__':
    if any(a in ('--help', '-h') for a in sys.argv[1:]):
        print((__doc__ or '').strip())
        sys.exit(0)
    sys.exit(main(sys.argv[1:]))
