#!/usr/bin/env python3
"""Find every place a practice is cited, across every source a repo declares.

A practice that is renamed, retired, deduplicated into another set, deleted,
or has its Rule reworded is only half changed at its own commit. The other
half is every citation of it: in the repository that changed it, in every
practice set that repository resolves, and in every consuming repository that
vendors any of them. Nothing used to look. The go-merge -> go-update rename
(2026-09-26) landed clean here and left the private sets still pointing at
`go-merge`, which is where it surfaced -- in the sets, a day later.

This module is the one place that answers "who cites this practice", so the
three things that need the answer ask it rather than keeping copies:

  * precedent_check.py's `practice-change-propagates` check, which fails on a
    LIVE citation of a practice in force nowhere (or one that now only
    forwards to a different slug) in a file the checking repo owns;
  * the merge gate, where a session that changed a practice is shown every
    citation of it in every declared source (`--changed-since BASE`);
  * Update Vendors, where a consuming repo is shown what the update withdrew
    or reworded and where its own files still cite it
    (precedent_update.py).

A citation is LIVE unless it is plainly history: frontmatter lineage fields,
a Story/History-style section, a record directory (decisions/, gotchas/,
closed items), a withdrawn practice's own stub, or a line that itself narrates
the change ("renamed", "retired", "superseded", or naming the successor
beside it). History is the record of what used to be true and is left alone.

Usage:
  precedent_practice_refs.py SLUG [SLUG ...]      every citation of these
  precedent_practice_refs.py --changed-since REF  slugs this branch changed
  precedent_practice_refs.py --withdrawn          every live citation, in
                                                  every declared source, of a
                                                  practice no longer in force
  add --all to include history hits, --json for machine output,
  --handoff to print a paste-ready block for repos this session cannot push.

practice: practice-change-propagates
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

import build_views as bv            # noqa: E402
import precedent_resolve as pr      # noqa: E402

TEXT_EXTS = {'.md', '.py', '.sh', '.json', '.yml', '.yaml', '.txt', '.toml'}

# A heading that opens a section recording the past. Everything under it, to
# the next heading at the same or a higher level, is history.
HISTORY_HEADING = re.compile(
    r'^(#{1,6})\s+[^\n]*\b(story|history|revisions?|revised|changelog|'
    r'lineage|withdrawn|retired|superseded|deduplicated|renamed|log|'
    r'incident|what happened|absorbed|consolidat\w*|came from)\b', re.I)

# Directories and files that are records by nature: a decision, a gotcha's
# story, an open or closed item, a plan or audit under spec/, a retirement
# map. Their citations describe what was true when they were written, and a
# plan that names a practice since renamed is still an accurate plan.
HISTORY_PATH = re.compile(
    r'(^|/)(decisions|gotchas|records?|checkins?|writeups?|spec|todo)/|'
    r'(^|/)todo/CLOSED\.md$|CHANGELOG|RETIREMENT|_FINDINGS', re.I)

# A line narrating the change itself is lineage, not a live citation.
LINEAGE_WORDS = re.compile(
    r'\b(renam\w*|retir\w*|supersed\w*|deduplicat\w*|withdr[ae]w\w*|'
    r'formerly|was called|used to|replac\w*|moved to|merged into|folded into|'
    r'absorbed|successor|predecessor|in_force_at|supersedes)\b', re.I)

GENERATED_MARK = re.compile(r'do not hand-edit|generated by|GENERATED', re.I)

_SLUG = r'[a-z0-9]+(?:-[a-z0-9]+)*'
# Each pattern captures a slug. Only slugs in the asked-for set are reported,
# so a loose pattern costs nothing but a lookup. ORDER MATTERS: one line
# reports a slug once, under the first form that matches, and a link written
# [`slug`](slug.md) must count as the link it is, not as the backticks inside
# it.
REF_PATTERNS = (
    ('link', re.compile(
        r'\]\((?:\.\./|\./)?(?:[^)\s]*/practices/|practices/)?(' + _SLUG +
        r')\.md(?:#[^)\s]*)?\)')),
    ('show', re.compile(r'precedent_show\.py\s+(?:--\S+\s+)*(' + _SLUG + r')')),
    ('cite', re.compile(r'practice:\s*(' + _SLUG + r')\b')),
    ('backtick', re.compile(r'`(' + _SLUG + r')(?:\.md)?`')),
)


def _git(root, *args):
    return subprocess.run(['git', '-C', str(root), *args],
                          capture_output=True, text=True)


def own_live_slugs(repo):
    """Slugs in force in `repo`'s OWN practice trees. A practice set does not
    declare itself as a source -- its precedent.json names the others -- so
    resolve() run from inside a set never sees the set's own practices, and
    without this every one of them that another set deduplicates would read
    as withdrawn there. Found 2026-09-27 on the first run against the real
    sets: `rule-links`, active in the set asking, reported in force nowhere."""
    repo = Path(repo)
    out = set()
    for d in ('practices', 'local/practices'):
        for f in (repo / d).glob('*.md'):
            try:
                head = f.read_text(encoding='utf-8', errors='ignore')
            except OSError:
                continue
            if not _practice_withdrawn(head):
                out.add(f.stem)
    return out


def resolved(repo):
    """resolve() over what `repo` declares, with the repo's own in-force
    practices counted as in force, or raise pr.ResolveError."""
    res = pr.resolve(pr.load_config(Path(repo)))
    res['own_live'] = own_live_slugs(repo)
    return res


def withdrawn_map(res):
    """-> {slug: {'status', 'successor', 'source'}} for every slug some
    source carries that is in force NOWHERE. `successor` is the slug in force
    that a citation should name instead, or None when the rule went to the
    engine, to nowhere, or nowhere is recorded.

    A deduplicated copy whose `in_force_at:` names its OWN slug is a
    declaration that another source carries the rule. When that source is
    not visible from here (a set declaring only some of its siblings), the
    slug is unknown rather than withdrawn, and it is left out: calling it
    withdrawn would refuse a correct citation on the strength of what this
    repository happens not to declare."""
    live, retired = res['practices'], res.get('retired', [])
    own = res.get('own_live') or set()
    out = {}
    for p in retired:
        slug = p['slug']
        if slug in live or slug in own:
            continue                    # another source still carries it
        status = bv.practice_status(p['fm'])
        succ = None
        if status == bv.DEDUPLICATED_STATUS:
            succ = pr.follow_in_force_at(slug, live, retired)
        else:
            tgt = bv._json_str(p['fm'].get('in_force_at', '')) or ''
            if tgt and tgt not in (bv.IN_FORCE_AT_ENGINE, bv.IN_FORCE_AT_NOWHERE):
                succ = pr.follow_in_force_at(tgt, live, retired)
        if succ is None and status == bv.DEDUPLICATED_STATUS and \
                (bv._json_str(p['fm'].get('in_force_at', '')) or '') == slug:
            continue                    # lives in a source not visible here
        prior = out.get(slug)
        if prior is None or (prior['successor'] is None and succ):
            out[slug] = {'status': status, 'successor': succ,
                         'source': p.get('source')}
    return out


def _tracked(root):
    r = _git(root, 'ls-files', '-z')
    if r.returncode != 0:
        return []
    return [f for f in r.stdout.split('\0') if f]


def _is_generated(lines):
    return any(GENERATED_MARK.search(l) for l in lines[:6])


def scan_file(path, rel, slugs, successors=None, stub_slug=None,
              file_is_history=False):
    """-> [(lineno, slug, form, kind, section, line)] for citations of
    `slugs` in one file. kind is 'live' or 'history'; section is the nearest
    `## ` heading above the line ('' before the first one)."""
    successors = successors or {}
    own_slug = Path(rel).stem if rel.endswith('.md') and (
        rel.startswith('practices/') or '/practices/' in rel) else None
    try:
        text = Path(path).read_text(encoding='utf-8', errors='ignore')
    except OSError:
        return []
    if not any(s in text for s in slugs):
        return []
    lines = text.splitlines()
    path_is_history = bool(HISTORY_PATH.search(rel))
    is_practice = '/practices/' in '/' + rel and rel.endswith('.md')
    out = []
    in_fm = is_practice and lines[:1] == ['---']
    hist_level = None                   # heading depth of an open history section
    fence = False
    section = ''
    for i, line in enumerate(lines, 1):
        if in_fm and i > 1 and line.strip() == '---':
            in_fm = False
            continue
        stripped = line.lstrip()
        if stripped.startswith(('```', '~~~')):
            fence = not fence
        if not fence and rel.endswith('.md'):
            h = re.match(r'^(#{1,6})\s', line)
            if h:
                depth = len(h.group(1))
                if depth == 2:
                    section = line[3:].strip()
                if hist_level is not None and depth <= hist_level:
                    hist_level = None
                if hist_level is None and HISTORY_HEADING.match(line):
                    hist_level = depth
        seen = set()
        for form, rx in REF_PATTERNS:
            for m in rx.finditer(line):
                s = m.group(1)
                if s not in slugs or (s, i) in seen:
                    continue
                seen.add((s, i))
                succ = successors.get(s)
                history = (in_fm or path_is_history or file_is_history
                           or hist_level is not None
                           or s == stub_slug
                           # a practice naming its OWN predecessor is lineage
                           # by definition, whatever section it sits in
                           or (succ is not None and succ == own_slug)
                           or bool(LINEAGE_WORDS.search(line))
                           or (succ is not None and succ != s and
                               re.search(r'\b' + re.escape(succ) + r'\b', line)))
                out.append((i, s, form, 'history' if history else 'live',
                            section, line.strip()))
    return out


def _practice_withdrawn(text):
    """True when a practice file's frontmatter says it is not in force. Fails
    closed the way build_views.is_in_force does: anything but `active` is
    withdrawn, and a file with no status is active."""
    m = re.search(r'^status:\s*"?([\w-]+)', text.split('\n---', 1)[0], re.M)
    return bool(m) and m.group(1) != 'active'


def scan_root(root, slugs, successors=None, only_md=True, skip=()):
    """-> [(rel, lineno, slug, form, kind, section, line)] across a repo's
    tracked files. `skip` is a set of repo-relative paths (or prefixes ending
    in '/') this repo received rather than wrote.

    Markdown only by default: code comments that name an old slug are nearly
    all lineage ("this guard exists because go-merge ..."), and a code
    citation that must resolve is code-cites-practice's to check."""
    root = Path(root)
    out = []
    prefixes = tuple(p for p in skip if p.endswith('/'))
    exact = {p for p in skip if not p.endswith('/')}
    for rel in _tracked(root):
        ext = Path(rel).suffix.lower()
        if ext not in TEXT_EXTS or (only_md and ext != '.md'):
            continue
        if rel in exact or rel.startswith(prefixes):
            continue
        p = root / rel
        try:
            text = p.read_text(encoding='utf-8', errors='ignore')
        except OSError:
            continue
        if not any(x in text for x in slugs):
            continue
        is_practice = rel.endswith('.md') and (
            rel.startswith('practices/') or '/practices/' in rel)
        stub = p.stem if is_practice and p.stem in slugs else None
        # A withdrawn practice's whole text is history: the resolver drops it,
        # so nothing it says reaches a session or a consumer.
        withdrawn_file = is_practice and _practice_withdrawn(text)
        hits = scan_file(p, rel, slugs, successors, stub_slug=stub,
                         file_is_history=withdrawn_file)
        gen = _is_generated(text.splitlines())
        for (ln, s, form, kind, section, line) in hits:
            out.append((rel, ln, s, form,
                        'generated' if gen and kind == 'live' else kind,
                        section, line))
    return out


def must_fix(row, withdrawn=None):
    """True for a citation the check refuses: a live POINTER to a withdrawn
    practice -- a link, or a precedent_show.py command, which a reader follows
    to get the rule and lands on a stub or nothing -- anywhere in live text,
    or any live mention inside a practice's own `## Rule`, which is the text a
    session loads and acts on. A bare backticked name elsewhere is often
    lineage the heuristics cannot see ("exactly as `session-text` drew this
    line"), so it is listed for a session to read, never refused."""
    rel, _ln, slug, form, kind, section, _line = row
    if kind != 'live' or (withdrawn is not None and slug not in withdrawn):
        return False
    if form in ('link', 'show'):
        return True
    return rel.endswith('.md') and section == 'Rule' and (
        rel.startswith('practices/') or '/practices/' in rel)


def received_paths(root):
    """Paths in `root` it received from somewhere else and must not edit:
    materialized practices and checks of other sources (MANIFEST.json), the
    vendored engine (tools/ENGINE_MANIFEST.json), mirrored upstream trees."""
    root = Path(root)
    skip = set()
    try:
        m = json.loads((root / 'MANIFEST.json').read_text(encoding='utf-8'))
        local = {s.get('name') for s in (m.get('sources') or [])
                 if isinstance(s, dict) and s.get('level') == 'repo-local'}
        for e in (m.get('practices') or []):
            if isinstance(e, dict) and e.get('slug') and e.get('source') not in local:
                skip.add(f"practices/{e['slug']}.md")
        for e in (m.get('checks') or []):
            if isinstance(e, dict) and e.get('path') and e.get('source') not in local:
                skip.add(e['path'])
    except (ValueError, OSError):
        pass
    try:
        em = json.loads((root / 'tools' / 'ENGINE_MANIFEST.json').read_text(
            encoding='utf-8'))
        skip |= {f'tools/{f}' for f in (em.get('files') or [])}
    except (ValueError, OSError):
        pass
    try:
        skip |= {p if p.endswith('/') else p + '/'
                 for p in pr.mirrored_prefixes(root)}
    except Exception:                               # practice: fail-gracefully
        pass
    return skip


def source_roots(repo):
    """[(name, Path)] -- this repo first, then every declared source that is
    its own directory (a repo-local source inside the repo is covered by the
    repo itself)."""
    repo = Path(repo).resolve()
    out, seen = [('this repository', repo)], {repo}
    try:
        sources = pr.load_config(repo)
    except Exception:                               # practice: fail-gracefully
        return out
    for s in sources:
        try:
            p = (repo / s['path']).resolve()
        except Exception:
            continue
        if p in seen or not p.is_dir() or repo in p.parents:
            continue
        seen.add(p)
        out.append((s.get('name') or p.name, p))
    return out


def _rule_text(text):
    """The Rule section, normalized so that repointing a link or rewrapping a
    paragraph does not count as rewording the rule."""
    m = re.search(r'^## Rule\s*\n(.*?)(?=^## |\Z)', text, re.M | re.S)
    body = m.group(1) if m else ''
    body = re.sub(r'\]\([^)]*\)', ']', body)
    return ' '.join(body.split())


def changed_slugs(repo, base, staged=False):
    """-> {slug: what} for every practice withdrawn, deleted, renamed away,
    or whose Rule text changed: on this branch against `base`, or, with
    `staged`, in what is staged against `base` (Update Vendors: the update
    has been written and staged, not yet committed)."""
    repo = Path(repo)
    if staged:
        rng = ['--cached', base]
    else:
        # Against the merge base and the WORKING TREE, so a session asking
        # before it commits sees its own edits too.
        mb = _git(repo, 'merge-base', base, 'HEAD')
        if mb.returncode != 0:
            raise RuntimeError(f'no merge base with {base}: {mb.stderr.strip()}')
        base = mb.stdout.strip()
        rng = [base]
    r = _git(repo, 'diff', '--name-status', '--find-renames', *rng,
             '--', 'practices/*.md', 'local/practices/*.md')
    if r.returncode != 0:
        raise RuntimeError(f'could not diff against {base}: {r.stderr.strip()}')
    out = {}
    for line in r.stdout.splitlines():
        parts = line.split('\t')
        code = parts[0]
        if code.startswith('R'):
            out[Path(parts[1]).stem] = f'renamed to {Path(parts[2]).stem}'
            continue
        path = parts[-1]
        slug = Path(path).stem
        if code == 'D':
            out[slug] = 'deleted'
            continue
        if code != 'M':
            continue
        old = _git(repo, 'show', f'{base}:{path}').stdout
        if staged:
            new = _git(repo, 'show', f':{path}').stdout
        else:
            try:
                new = (repo / path).read_text(encoding='utf-8')
            except OSError:
                continue
        was = re.search(r'^status:\s*"?(\w+)', old, re.M)
        now = re.search(r'^status:\s*"?(\w+)', new, re.M)
        was = was.group(1) if was else 'active'
        now = now.group(1) if now else 'active'
        if was == 'active' and now != 'active':
            out[slug] = f'now {now}'
        elif now == 'active' and _rule_text(old) != _rule_text(new):
            out[slug] = 'Rule reworded'
    return out


def _report(rows_by_root, show_all, successors, withdrawn=()):
    total_live = 0
    for name, root, rows in rows_by_root:
        shown = [r for r in rows if show_all or r[4] != 'history']
        if not shown:
            continue
        print(f'\n== {name} ({root})')
        for row in shown:
            rel, ln, s, form, kind, section, line = row
            succ = successors.get(s)
            hint = f' -> cite `{succ}`' if succ else ''
            total_live += kind == 'live'
            if s not in withdrawn:
                # still in force: its Rule changed, so this is to be READ
                tag = 'read' if kind == 'live' else kind
            else:
                tag = 'MUST FIX' if must_fix(row, withdrawn) else kind
            print(f'  [{tag}] {rel}:{ln}  `{s}`{hint}')
            print(f'      {line[:160]}')
    return total_live


def _handoff(rows_by_root, successors, why, withdrawn=()):
    blocks = [(n, r, [x for x in rows if x[4] == 'live'])
              for n, r, rows in rows_by_root[1:]]
    blocks = [b for b in blocks if b[2]]
    if not blocks:
        return
    print('\n--- handoff (for a session rooted in the first repository below, '
          'with the others attached) ---')
    print(f'{why} Fix each live citation below so it names the practice now '
          f'in force (or, where none is, says in prose what the rule covered). '
          f'Leave history -- Story sections, lineage lines, records -- alone. '
          f'Then run `python3 tools/precedent_practice_refs.py --withdrawn` in '
          f'each repository and confirm it reports no live citation.')
    for name, root, rows in blocks:
        print(f'\n{name}:')
        for row in rows:
            rel, ln, s = row[:3]
            succ = successors.get(s)
            print(f'  - {rel}:{ln} cites `{s}`'
                  + (' [must fix]' if must_fix(row, withdrawn) else
                     ' [read: its Rule changed]' if s not in withdrawn else '')
                  + (f' -> `{succ}`' if succ else ' (in force nowhere)'))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('slugs', nargs='*')
    ap.add_argument('--repo', default='.')
    ap.add_argument('--changed-since', metavar='REF')
    ap.add_argument('--staged', action='store_true',
                    help='with --changed-since, compare what is staged '
                         '(Update Vendors) rather than this branch\'s commits')
    ap.add_argument('--withdrawn', action='store_true')
    ap.add_argument('--all', action='store_true', help='include history hits')
    ap.add_argument('--json', action='store_true')
    ap.add_argument('--handoff', action='store_true')
    ap.add_argument('--code', action='store_true',
                    help='search code and config too, not only markdown')
    a = ap.parse_args(argv)
    repo = Path(a.repo).resolve()

    try:
        res = resolved(repo)
        wmap = withdrawn_map(res)
    except Exception as e:                          # practice: fail-gracefully
        print(f'precedent_practice_refs: could not resolve sources ({e}); '
              f'searching this repository only, with no successor names.',
              file=sys.stderr)
        res, wmap = None, {}
    successors = {s: v['successor'] for s, v in wmap.items() if v['successor']}

    why = {}
    if a.changed_since:
        try:
            why = changed_slugs(repo, a.changed_since, staged=a.staged)
        except RuntimeError as e:
            print(f'precedent_practice_refs: {e}', file=sys.stderr)
            return 2
    for s in a.slugs:
        why.setdefault(s, 'asked for')
    if a.withdrawn:
        for s, v in wmap.items():
            why.setdefault(s, f"{v['status']}")
    if not why:
        if a.json:
            print(json.dumps({'slugs': {}, 'successors': successors,
                              'hits': []}, indent=2))
            return 0
        if a.changed_since:
            print('No practice was renamed, withdrawn, deleted or reworded '
                  f'since {a.changed_since}.')
            return 0
        ap.error('name a slug, or pass --changed-since REF or --withdrawn')
    slugs = set(why)

    rows_by_root = []
    for name, root in source_roots(repo):
        rows = scan_root(root, slugs, successors, only_md=not a.code,
                         skip=received_paths(root))
        rows_by_root.append((name, root, rows))

    if a.json:
        print(json.dumps({
            'slugs': why, 'successors': successors,
            'hits': [{'source': n, 'root': str(r), 'file': x[0], 'line': x[1],
                      'slug': x[2], 'form': x[3], 'kind': x[4],
                      'section': x[5], 'must_fix': must_fix(x, wmap),
                      'text': x[6]}
                     for n, r, rows in rows_by_root for x in rows]}, indent=2))
        return 0

    print('Practices looked up:')
    for s in sorted(why):
        succ = successors.get(s)
        print(f'  {s}: {why[s]}' + (f' (in force as `{succ}`)' if succ else ''))
    live = _report(rows_by_root, a.all, successors, wmap)
    reworded = [s for s, w in why.items() if w == 'Rule reworded']
    print(f'\n{live} live citation(s).'
          + (' A reworded Rule keeps its slug, so no check can tell whether a '
             'citation still describes it -- read each live one above.'
             if reworded else ''))
    if a.handoff:
        _handoff(rows_by_root, successors,
                 'A practice in the universal set changed: '
                 + '; '.join(f'`{s}` {w}' for s, w in sorted(why.items()))
                 + '.', wmap)
    return 0


if __name__ == '__main__':
    sys.exit(main())
