#!/usr/bin/env python3
"""Rebuilds the generated files whose inputs a commit touches, and stages them -- run by the commit backstop, never refuses a commit

precedent_regenerate.py -- the commit-time half of "generated files are
never hand-edited" (spec/GENERATED_FILES_PLAN.md step 3; Morgan,
2026-10-03: generated files are always generated, and "auto-updated" as
their sources change).

    python3 tools/precedent_regenerate.py --staged   what the commit backstop runs
    python3 tools/precedent_regenerate.py --all      rebuild every listed file now

Reads the repository's list of generated files, tools/generated_files.json.
An entry is rebuilt when a staged path matches one of its inputs: its
`inputs` globs when it names them, else its `edit_instead` glob, plus the
tool that generates it and the list itself. Each distinct `regenerate`
command runs once. An entry with no `check` (a log or a snapshot nothing
offline can rebuild) is never run.

It FIXES a commit and never refuses one: every failure is said and the
commit goes ahead, and the push check still judges what was committed.

It never loses work (practice: repair-cannot-discard-work):
  * a generated file that has changes of the session's own that are not
    staged is rebuilt but NOT staged, and said, so nothing unstaged is
    swept into the commit -- AGENTS.md carries hand-written text around its
    generated blocks;
  * a generated file already changed in the checkout, which the rebuild
    then changes again, is copied first to .git/precedent-regenerate/, and
    said: most often an earlier rebuild, sometimes a hand edit -- the
    mistake this exists to prevent -- but either way it is kept, never
    thrown away.
"""
import fnmatch
import json
import pathlib
import os
import shlex
import shutil
import subprocess
import sys

REGISTRY = 'tools/generated_files.json'
# Trees that are COPIES of another repository's files -- the classic
# vendored catalogue mirror. A labelled file there was generated upstream and
# is copied here; it is the upstream list's to name, never this repository's.
VENDORED_TREES = ('process/upstream/',)


# What a git hook's environment carries that points every git command at the
# repository being committed. The rebuilds this runs read OTHER repositories
# too -- build_views asks each declared source's own clone what it is -- and
# with GIT_DIR set, `git -C <that clone>` answered about this one instead.
# Measured 2026-10-04: a practice set's commit, through this fixer, rebuilt
# AGENTS.md with the person's individual practices inlined (11 resident,
# ~1214 tokens) where a plain build defers them all (1 resident, ~62); the
# set's push check refused it, and every set's Update Vendors failed on it.
# The rebuild commands get an environment without them; this fixer's own
# `git add` and `git diff` keep the hook's, so they stage into the index the
# commit is being made from.
HOOK_GIT_ENV = ('GIT_DIR', 'GIT_INDEX_FILE', 'GIT_WORK_TREE', 'GIT_PREFIX',
                'GIT_COMMON_DIR', 'GIT_OBJECT_DIRECTORY',
                'GIT_ALTERNATE_OBJECT_DIRECTORIES', 'GIT_QUARANTINE_PATH')


def _tool_env():
    """-> os.environ without the variables a git hook sets (HOOK_GIT_ENV)."""
    return {k: v for k, v in os.environ.items() if k not in HOOK_GIT_ENV}


def _git(root, *args):
    return subprocess.run(['git', '-C', str(root), *args],
                          capture_output=True, text=True)


def _entries(root):
    path = pathlib.Path(root) / REGISTRY
    if not path.is_file():
        return []
    try:
        return json.loads(path.read_text(encoding='utf-8')).get('files') or []
    except (ValueError, AttributeError):
        return []


def _inputs(entry):
    globs = list(entry.get('inputs') or ([entry['edit_instead']]
                                          if entry.get('edit_instead') else []))
    if entry.get('generated_by'):
        globs.append(entry['generated_by'])
    return globs + [REGISTRY]


def _label(text):
    """-> {generated_by, edit_instead} from a file's generated label: its
    front matter, or the older hidden comment, which names the generator
    only. None when the file carries no label."""
    import re
    head = text[:3000]
    if head.startswith('---\n'):
        end = head.find('\n---', 4)
        fm = head[:end if end > 0 else len(head)]
        g = re.search(r'^generated_by:\s*"?([^"\n]+?)"?\s*$', fm, re.M)
        if g:
            e = re.search(r'^edit_instead:\s*"?([^"\n]+?)"?\s*$', fm, re.M)
            return {'generated_by': g.group(1).strip(),
                    'edit_instead': e.group(1).strip() if e else None}
    m = re.search(r'<!-- GENERATED by (\S+)', head)
    return {'generated_by': m.group(1), 'edit_instead': None} if m else None


def labelled_entries(repo, engine_rel, listed=(), known=None):
    """-> list entries for every tracked Markdown file in `repo` that says it
    is generated and is not in `listed`, read from the file's own label, so
    a repository's list names everything it generates with nothing typed by
    hand (spec/GENERATED_FILES_PLAN.md G5). `known` maps (path, generator)
    to a fuller entry to use instead, for a label too old to name its
    source. A generator outside this engine is listed as it is named."""
    repo = pathlib.Path(repo)
    out = []
    for rel in _git(repo, 'ls-files', '*.md').stdout.splitlines():
        if rel in listed or rel.startswith(VENDORED_TREES):
            continue
        try:
            lab = _label((repo / rel).read_text(encoding='utf-8', errors='ignore'))
        except OSError:
            continue
        if not lab:
            continue
        gen = lab['generated_by']
        if known and (rel, gen) in known:
            out.append(dict(known[(rel, gen)]))
            continue
        tool = f'{engine_rel}/{pathlib.PurePosixPath(gen).name}'
        out.append({'path': rel, 'generated_by': gen,
                    'edit_instead': lab['edit_instead'],
                    'regenerate': f'python3 {tool}', 'check': [tool, '--check']})
    return out


def due(entries, staged):
    """-> the entries whose inputs one of `staged` matches, in list order.
    An entry that cannot be rebuilt offline (no `check`) is never due."""
    out = []
    for e in entries:
        if not e.get('check') or not e.get('regenerate'):
            continue
        if any(fnmatch.fnmatch(p, g) for p in staged for g in _inputs(e)):
            out.append(e)
    return out


def _blob(root, spec):
    r = subprocess.run(['git', '-C', str(root), 'show', spec],
                       capture_output=True)
    return r.stdout if r.returncode == 0 else None


def regenerate(root, entries, say=print, stage=True):
    """Run each due entry's `regenerate` once and stage what it rewrote.
    -> the paths staged."""
    root = pathlib.Path(root)
    paths = sorted({e['path'] for e in entries})
    before = {p: (root / p).read_bytes() if (root / p).is_file() else None
              for p in paths}
    unstaged = {p for p in paths
                if _git(root, 'diff', '--quiet', '--', p).returncode != 0}
    for cmd in dict.fromkeys(e['regenerate'] for e in entries):
        argv = shlex.split(cmd)
        if argv and argv[0] in ('python3', 'python'):
            argv[0] = sys.executable
        r = subprocess.run(argv, cwd=str(root), capture_output=True, text=True,
                           env=_tool_env())
        if r.returncode != 0:
            say(f'precedent_regenerate: `{cmd}` failed, so what it writes was '
                f'left as it was; the push check will say what is stale. '
                f'{(r.stdout + r.stderr).strip()[-300:]}')
    staged = []
    for p in paths:
        now = (root / p).read_bytes() if (root / p).is_file() else None
        if now == before[p]:
            continue
        if p in unstaged:
            say(f'precedent_regenerate: rebuilt {p}, but it also has changes of '
                f'yours that are not staged, so it was NOT added to this commit. '
                f'Stage it yourself once you have looked: git add {p}')
            continue
        if before[p] is not None and before[p] != _blob(root, f'HEAD:{p}'):
            keep = root / '.git' / 'precedent-regenerate' / p
            gd = _git(root, 'rev-parse', '--absolute-git-dir').stdout.strip()
            if gd:
                keep = pathlib.Path(gd) / 'precedent-regenerate' / p
            keep.parent.mkdir(parents=True, exist_ok=True)
            keep.write_bytes(before[p])
            say(f'precedent_regenerate: {p} was already changed in this '
                f'checkout and the rebuild changed it again; the earlier version '
                f'is kept at {keep}. It is generated: change its sources, never '
                f'the file.')
        if stage:
            _git(root, 'add', '--', p)
            staged.append(p)
    if staged:
        say(f'precedent_regenerate: rebuilt and staged {", ".join(staged)} '
            f'(their sources changed in this commit).')
    return staged


# GENERATED BLOCKS INSIDE HAND-WRITTEN DOCUMENTS (<!--gen:NAME-->), which
# doc_sync.py's PAIRS lists rather than the list above. They are generated
# content too, so a commit that could move what they report refreshes them
# (Morgan, 2026-10-03: generated files are auto-updated as their sources
# change). Found that day: a practice gained a ## Detail, and
# spec/LOADER.md's count of practices carrying one went stale with nothing
# rebuilding it. doc_sync.py --write rewrites only blocks that drifted.
BLOCK_INPUTS = ('practices/*.md', 'tools/*.py', '*.json')


def refresh_blocks(root, staged, say=print):
    """Run doc_sync.py --write when a staged path is one a block's script
    reads, and stage each document it rewrote. -> the documents staged. A
    document with unstaged changes of its own is rewritten but not staged,
    and said, as for a whole generated file."""
    root = pathlib.Path(root)
    tool = root / 'tools' / 'doc_sync.py'
    if not tool.is_file() or not any(fnmatch.fnmatch(p, g) for p in staged
                                     for g in BLOCK_INPUTS):
        return []
    dirty = set(_git(root, 'diff', '--name-only').stdout.split())
    r = subprocess.run([sys.executable, str(tool), '--write'], cwd=str(root),
                       capture_output=True, text=True, env=_tool_env())
    written = sorted({l.split()[2] for l in (r.stdout + r.stderr).splitlines()
                      if l.startswith('[doc_sync] WROTE ') and len(l.split()) > 2})
    staged_now = []
    for rel in written:
        if rel in dirty:
            say(f'precedent_regenerate: rebuilt the generated blocks in {rel}, but it '
                f'also has changes of yours that are not staged, so it was NOT added '
                f'to this commit. Stage it yourself once you have looked: git add {rel}')
            continue
        _git(root, 'add', '--', rel)
        staged_now.append(rel)
    if staged_now:
        say(f'precedent_regenerate: rebuilt and staged the generated blocks in '
            f'{", ".join(staged_now)}.')
    return staged_now


def main(argv):
    if argv[:1] in (['--help'], ['-h']):
        print(__doc__.strip())
        return 0
    if not argv or argv[0] not in ('--staged', '--all') or len(argv) > 1:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    top = _git(pathlib.Path.cwd(), 'rev-parse', '--show-toplevel').stdout.strip()
    if not top:
        return 0
    entries = _entries(top)
    if argv[0] == '--all':
        regenerate(top, [e for e in entries if e.get('check') and e.get('regenerate')],
                   stage=False)
        return 0
    staged = [l for l in _git(top, 'diff', '--cached', '--name-only').stdout.splitlines() if l]
    todo = due(entries, staged)
    if todo:
        regenerate(top, todo, say=lambda m: print(m, file=sys.stderr))
    refresh_blocks(top, staged, say=lambda m: print(m, file=sys.stderr))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main(sys.argv[1:]))
    except Exception as exc:  # a fixer never blocks a commit
        print(f'precedent_regenerate: skipped ({exc})', file=sys.stderr)
        sys.exit(0)
